### ISSUE TITLE
VISA Error

### ISSUE THREAD

**Issue by codesol7** [paymentcardtools/smartcard-reader#1]
Everything works perfectly with Mastercard but when I try to scan any VISA it give me this error
# Missing data for GPO processing, check TERMCONFIG dict
Anyone has any idea on how to solve that?

**Comment by paymentcardtools** [comment]
in scard.py there is a TERMCONFIG dict defined with the data for GPO. This error indicates that some of the data (tag) is missing in the dict and has to be added.
Please share the fragment of output of reading the card, or at least content of Tag 9F38 (PDOL). You can use the https://paymentcardtools.com/emv-misc/dols tool to parse the PDOL and see what is expected and what is currently missing in TERMCONFIG dict.

**Comment by codesol7** [comment]
9F38 Processing Options Data Object List (PDOL)
         9F66049F02069F03069F1A0295055F2A029A039C019F3704
      BF0C File Control Information (FCI) Issuer Discretionary Data
         9F5A Application Program Identifier (Program ID)
            3109780440
         9F0A Application Selection Registered Proprietary Data
            0001050100000000
         BF63 Unknown
            DF20 Unknown
               80
=
PDOL: 9F66049F02069F03069F1A0295055F2A029A039C019F3704
# Missing data for GPO processing, check TERMCONFIG dict

**Comment by paymentcardtools** [comment]
try the latest code. The TERMCONFIG has been extended.
Could you please let me know whether you read the card using the contactless reader?

**Comment by codesol7** [comment]
Still same error : 
* SELECT A0000000031010
>c-apdu: 00 A4 04 00 07 A0 00 00 00 03 10 10
sw 90 00
<r-apdu: 6F 6E 84 07 A0 00 00 00 03 10 10 A5 63 50 0A 56 69 73 61 20 44 65 62 69 74 87 01 01 5F 2D 08 65 6E 6C 76 72 75 64 65 9F 11 01 01 9F 12 0A 56 69 73 61 20 44 65 62 69 74 9F 38 18 9F 66 04 9F 02 06 9F 03 06 9F 1A 02 95 05 5F 2A 02 9A 03 9C 01 9F 37 04 BF 0C 1A 9F 5A 05 31 09 78 04 40 9F 0A 08 00 01 05 01 00 00 00 00 BF 63 04 DF 20 01 80
=
6F File Control Information (FCI) Template
   84 Dedicated File (DF) Name
      A0000000031010
   A5 File Control Information (FCI) Proprietary Template
      50 Application Label
         56697361204465626974 (Visa Debit)
      87 Application Priority Indicator
         01
      5F2D Language Preference
         656E6C7672756465 (enlvrude)
      9F11 Issuer Code Table Index
         01
      9F12 Application Preferred Name
         56697361204465626974 (Visa Debit)
      9F38 Processing Options Data Object List (PDOL)
         9F66049F02069F03069F1A0295055F2A029A039C019F3704
      BF0C File Control Information (FCI) Issuer Discretionary Data
         9F5A Application Program Identifier (Program ID)
            3109780440
         9F0A Application Selection Registered Proprietary Data
            0001050100000000
         BF63 Unknown
            DF20 Unknown
               80
=
PDOL: 9F66049F02069F03069F1A0295055F2A029A039C019F3704
* GET PROCESSING OPTIONS
>c-apdu: 80 A8 00 00 23 83 21 10 00 00 00 00 00 00 00 01 00 00 00 00 00 00 00 05 28 00 00 00 00 00 09 78 23 06 05 00 01 23 45 67
sw 69 85
! Unable to process application

**Comment by paymentcardtools** [comment]
it is another error, obviously. Status word set to 69 85 that means "Conditions of use not satisfied". Try to run with latest code, I've adjusted a bit TTQ value

**Comment by codesol7** [comment]
Now it reads it perfectly, thank you, but I still encounter same error, this time when scanning trough Apple Pay/Gpay.
Couldn`t be written an exception that handles every unknown card? Thank you very much

**Comment by paymentcardtools** [comment]
you're welcome.
Please note that this project is only tested for contact read and it is mentioned in the descritpion. Contacless mode (including apple/google pay) is not yet supported/tested.
Please share the log of the error for apple/google pay, I will take a look

**Comment by codesol7** [comment]
That would be for Mastercard 

6F File Control Information (FCI) Template
   84 Dedicated File (DF) Name
      A0000000041010
   A5 File Control Information (FCI) Proprietary Template
      50 Application Label
         4D415354455243415244 (MASTERCARD)
      87 Application Priority Indicator
         01
      5F2D Language Preference
         726F656E (roen)
      9F38 Processing Options Data Object List (PDOL)
         9F1D089F1A02
      BF0C File Control Information (FCI) Issuer Discretionary Data
         9F6E Third Party Data / Form Factor Indicator
            06420000323100
         9F4D Log Entry
            0B0A
         9F0A Application Selection Registered Proprietary Data
            00010101
=
PDOL: 9F1D089F1A02 
# Missing data for GPO processing, check TERMCONFIG dict


And this one for Visa 


6F File Control Information (FCI) Template
   84 Dedicated File (DF) Name
      A0000000031010
   A5 File Control Information (FCI) Proprietary Template
      9F38 Processing Options Data Object List (PDOL)
         9F66049F02069F03069F1A0295055F2A029A039C019F37049F4E14
      BF0C File Control Information (FCI) Issuer Discretionary Data
         9F5A Application Program Identifier (Program ID)
            3108400826
         BF63 Unknown
            DF20 Unknown
               80
         9F0A Application Selection Registered Proprietary Data
            00010101
      50 Application Label
         56697361204445424954 (Visa DEBIT)
=
PDOL: 9F66049F02069F03069F1A0295055F2A029A039C019F37049F4E14 
# Missing data for GPO processing, check TERMCONFIG dict

Cheers

**Comment by paymentcardtools** [comment]
try again with the recent code

**Comment by codesol7** [comment]
Perfect for Mastercard, new issue for VISA 

* SELECT 1PAY.SYS.DDF01
>c-apdu: 00 A4 04 00 0E 31 50 41 59 2E 53 59 53 2E 44 44 46 30 31
sw 6A 82
! PSE not found
Trying AID: A0000000031010
* SELECT A0000000031010
>c-apdu: 00 A4 04 00 07 A0 00 00 00 03 10 10
sw 6A 82
Trying AID: A0000000041010
* SELECT A0000000041010
>c-apdu: 00 A4 04 00 07 A0 00 00 00 04 10 10
sw 6A 82
! No application to process

**Comment by paymentcardtools** [comment]
I've extended list of AIDs candidates. Try now

**Comment by codesol7** [comment]
Solved, thank you !
